// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeberMotosWF.DataBase;

#nullable disable

namespace WeberMotosWF.Migrations
{
    [DbContext(typeof(OficinaDbContext))]
    [Migration("20250701022457_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WeberMotosWF.Models.Peca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PrecoVenda")
                        .HasColumnType("double precision");

                    b.Property<double>("UltimoPrecoCompra")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("pecas");
                });

            modelBuilder.Entity("WeberMotosWF.Models.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataManutencao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FotoMoto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("HorasTrabalhadas")
                        .HasColumnType("double precision");

                    b.Property<string>("ModeloMoto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlacaMoto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalVenda")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("vendas");
                });

            modelBuilder.Entity("WeberMotosWF.Models.VendaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PecaId")
                        .HasColumnType("integer");

                    b.Property<double>("PrecoPeca")
                        .HasColumnType("double precision");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("VendaId")
                        .HasColumnType("integer");

                    b.Property<int>("VendaId1")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PecaId");

                    b.HasIndex("VendaId");

                    b.HasIndex("VendaId1");

                    b.ToTable("vendaItens");
                });

            modelBuilder.Entity("WeberMotosWF.Models.VendaItem", b =>
                {
                    b.HasOne("WeberMotosWF.Models.Peca", "Peca")
                        .WithMany()
                        .HasForeignKey("PecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeberMotosWF.Models.Venda", null)
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeberMotosWF.Models.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("VendaId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peca");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("WeberMotosWF.Models.Venda", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
